openapi: 3.0.0
info:
  title: Task Service API
  version: 1.0.0

servers:
  - url: http://localhost:8083
    description: Localhost Task Service

paths:
  /create:
    post:
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTaskResponse'
        '403':
          description: User does not have permission
        '409':
          description: Task already exists

  /{task_id}:
    get:
      summary: Get task by ID
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseTaskResponse'
        '404':
          description: Task not found

  /all:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseListTaskResponse'

  /delete/{taskId}:
    delete:
      summary: Delete task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseMessage'
        '404':
          description: Task not found

components:
  schemas:

    CreateTaskRequest:
      type: object
      properties:
        taskName:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date-time
        teamId:
          type: integer
        assigneeUserIds:
          type: array
          items:
            type: integer
        createBy:
          type: integer
      required: [taskName, dueDate, teamId, createBy]

    TaskResponse:
      type: object
      properties:
        id:
          type: integer
        taskName:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date-time
        createAt:
          type: string
          format: date-time
        createBy:
          type: integer
        teamId:
          type: integer
        assigneeIds:
          type: array
          items:
            type: integer

    Receiver:
      type: object
      properties:
        id:
          type: integer
        nameAssignee:
          type: string
        email:
          type: string

    ApiResponseTaskResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        result:
          $ref: '#/components/schemas/TaskResponse'

    ApiResponseListTaskResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'

    ApiResponseMessage:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
