version: "3.8"

services:
  gateway:
    build:
      context: ./services/gateway
    ports:
      - "8888:8080"
    depends_on:
      - user-service
      - team-service
      - task-service
      - notification-service
    environment:
      PORT: 8080
      APP_SERVICES_USER: http://user-service:8080/user
      APP_SERVICES_TEAM: http://team-service:8080/team
      APP_SERVICES_TASK: http://task-service:8080/task
      APP_SERVICES_NOTIFICATION: http://notification-service:8080/notification

  user-service:
    build:
      context: ./services/user-service
    depends_on:
      - user-db
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  user-db:
    image: mysql:8
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_service
    ports:
      - "3307:3306"

  team-service:
    build:
      context: ./services/team-service
    depends_on:
      - team-db
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://team-db:3306/team_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  team-db:
    image: mysql:8
    container_name: team-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: team_service
    ports:
      - "3308:3306"

  task-service:
    build:
      context: ./services/task-service
    depends_on:
      - task-db
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://task-db:3306/task_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      APP_SERVICES_TEAM: http://team-service:8080/team
      APP_SERVICES_NOTIFICATION: http://notification-service:8080/notification
      APP_SERVICES_USER: http://user-service:8080/user

  task-db:
    image: mysql:8
    container_name: task-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task_service
    ports:
      - "3309:3306"

  notification-service:
    build:
      context: ./services/notification-service
    environment:
      PORT: 8080
      MAIL_HOST: smtp.gmail.com
      MAIL_USERNAME: your_email@gmail.com
      MAIL_PASSWORD: your_app_password
